=== beltram/stubr/schemas/stubr.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "description": "Unique stub identifier",
      "type": "string"
    },
    "uuid": {
      "description": "Unique stub identifier",
      "type": "string"
    },
    "priority": {
      "description": "Matching priority. Helps solving interlaced conditions (many stubs match the request). 1 is the highest priority, 255 the lowest. Defaults to 5.",
      "type": "integer"
    },
    "request": {
      "description": "Request matching",
      "type": "object",
      "properties": {
        "method": {
          "description": "Http method",
          "type": "string",
          "enum": [
            "GET",
            "HEAD",
            "POST",
            "PUT",
            "DELETE",
            "CONNECT",
            "OPTIONS",
            "TRACE",
            "PATCH",
            "ANY"
          ]
        },
        "urlPath": {
          "description": "Exact url matching",
          "type": "string",
          "format": "uri-reference"
        },
        "urlPathPattern": {
          "description": "Url matching by regex",
          "type": "string",
          "format": "regex"
        },
        "urlPattern": {
          "description": "Url and query parameters must match regex",
          "type": "string",
          "format": "regex"
        },
        "url": {
          "description": "Url and query parameters exact matching",
          "type": "string"
        },
        "queryParameters": {
          "description": "Query parameters",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "anyOf": [
                {
                  "type": "object",
                  "properties": {
                    "equalTo": {
                      "description": "Matching by equality",
                      "type": "string"
                    },
                    "absent": {
                      "description": "Must be absent",
                      "type": "boolean"
                    },
                    "contains": {
                      "description": "Must contain the given string",
                      "type": "string"
                    },
                    "matches": {
                      "description": "Must match the regex",
                      "type": "string",
                      "format": "regex"
                    },
                    "doesNotMatch": {
                      "description": "Must not match the regex",
                      "type": "string",
                      "format": "regex"
                    }
                  }
                }
              ]
            }
          }
        },
        "headers": {
          "description": "Request headers",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "anyOf": [
                {
                  "type": "object",
                  "properties": {
                    "equalTo": {
                      "description": "Matching by equality",
                      "type": "string"
                    },
                    "absent": {
                      "description": "Must be absent",
                      "type": "boolean"
                    },
                    "contains": {
                      "description": "Must contain the given string",
                      "type": "string"
                    },
                    "matches": {
                      "description": "Must match the regex",
                      "type": "string",
                      "format": "regex"
                    },
                    "doesNotMatch": {
                      "description": "Must not match the regex",
                      "type": "string",
                      "format": "regex"
                    }
                  }
                }
              ]
            }
          }
        },
        "basicAuth": {
          "description": "For exact Basic authorization request matching",
          "type": "object",
          "required": [
            "password",
            "username"
          ],
          "properties": {
            "username": {
              "description": "Basic username",
              "type": "string"
            },
            "password": {
              "description": "Basic password",
              "type": "string"
            }
          }
        },
        "jwtAuth": {
          "description": "For Bearer authorization request matching with a JWT",
          "type": "object",
          "properties": {
            "equalTo": {
              "description": "Plain JWT token without 'Bearer ' prefix",
              "type": "string"
            },
            "alg": {
              "type": "object",
              "description": "JWT algorithm request matching",
              "properties": {
                "equalTo": {
                  "type": "string",
                  "description": "JWT algorithm by strict equality",
                  "enum": [
                    "HS256",
                    "HS384",
                    "HS512",
                    "ES256",
                    "ES384",
                    "RS256",
                    "RS384",
                    "RS512",
                    "PS256",
                    "PS384",
                    "PS512",
                    "EdDSA"
                  ]
                }
              }
            },
            "payloadPatterns": {
              "description": "Allows defining many JWT payload matchers",
              "type": "array",
              "uniqueItems": true,
              "items": {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "equalToJson": {
                        "description": "JWT payload must be strictly equal to this",
                        "type": [
                          "object",
                          "array"
                        ]
                      }
                    }
                  },
                  {
                    "type": "object",
                    "properties": {
                      "matchesJsonPath": {
                        "description": "JWT payload must match this json path",
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "expression",
                      "contains"
                    ],
                    "properties": {
                      "expression": {
                        "description": "JWT payload must match this json path",
                        "type": "string"
                      },
                      "contains": {
                        "description": "Matched json path must contain this string",
                        "type": "string"
                      }
                    }
                  },
                  {
                    "type": "object",
                    "required": [
                      "expression",
                      "equalToJson"
                    ],
                    "properties": {
                      "expression": {
                        "description": "JWT payload must match this json path",
                        "type": "string"
                      },
                      "equalToJson": {
                        "description": "Matched json path must be equal to this",
                        "type": [
                          "object",
                          "array"
                        ]
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        "bodyPatterns": {
          "description": "Allows defining many request body matchers",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "equalToJson": {
                    "description": "Request body must be strictly equal to this",
                    "type": [
                      "object",
                      "array"
                    ]
                  },
                  "ignoreExtraElements": {
                    "description": "Ignore extra json fields supplied in request body",
                    "type": "boolean",
                    "default": false
                  },
                  "ignoreArrayOrder": {
                    "description": "Ignore array items order",
                    "type": "boolean",
                    "default": false
                  }
                }
              },
              {
                "type": "object",
                "properties": {
                  "matchesJsonPath": {
                    "description": "Request body must match this json path",
                    "type": "string",
                    "x-intellij-language-injection": {
                      "language": "JSONPath"
                    }
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "expression",
                  "contains"
                ],
                "properties": {
                  "expression": {
                    "description": "Request body must match this json path",
                    "type": "string",
                    "x-intellij-language-injection": {
                      "language": "JSONPath"
                    }
                  },
                  "contains": {
                    "description": "Matched json path must contain this string",
                    "type": "string"
                  }
                }
              },
              {
                "type": "object",
                "required": [
                  "expression",
                  "equalToJson"
                ],
                "properties": {
                  "expression": {
                    "description": "Request body must match this json path",
                    "type": "string",
                    "x-intellij-language-injection": {
                      "language": "JSONPath"
                    }
                  },
                  "equalToJson": {
                    "description": "Matched json path must be equal to this",
                    "type": [
                      "object",
                      "array"
                    ]
                  }
                }
              },
              {
                "type": "object",
                "properties": {
                  "binaryEqualTo": {
                    "description": "Binary equality of a byte array with the supplied Base64 representation",
                    "type": "string"
                  }
                }
              }
            ]
          }
        }
      }
    },
    "response": {
      "description": "Response templating",
      "type": "object",
      "properties": {
        "status": {
          "description": "Response status code",
          "type": "integer",
          "minimum": 100,
          "maximum": 599,
          "default": 200
        },
        "fixedDelayMilliseconds": {
          "description": "Local delay in milliseconds this stub will simulate",
          "type": "integer"
        },
        "body": {
          "description": "Text response body, adds 'Content-Type:application/text' header in the response",
          "type": "string",
          "x-intellij-language-injection": {
            "language": "Handlebars"
          }
        },
        "base64Body": {
          "description": "Binary Base 64 response body",
          "type": "string"
        },
        "bodyFileName": {
          "description": "Relative path to a .json or .txt file containing response body",
          "type": "string"
        },
        "jsonBody": {
          "description": "Json response body, adds 'Content-Type:application/json' header in the response",
          "type": [
            "object",
            "array"
          ],
          "patternProperties": {
            "^.*$": {
              "x-intellij-language-injection": {
                "language": "Handlebars"
              },
              "patternProperties": {
                "^.*$": {
                  "x-intellij-language-injection": {
                    "language": "Handlebars"
                  },
                  "patternProperties": {
                    "^.*$": {
                      "x-intellij-language-injection": {
                        "language": "Handlebars"
                      },
                      "patternProperties": {
                        "^.*$": {
                          "x-intellij-language-injection": {
                            "language": "Handlebars"
                          },
                          "patternProperties": {
                            "^.*$": {
                              "x-intellij-language-injection": {
                                "language": "Handlebars"
                              },
                              "patternProperties": {
                                "^.*$": {
                                  "x-intellij-language-injection": {
                                    "language": "Handlebars"
                                  },
                                  "patternProperties": {
                                    "^.*$": {
                                      "x-intellij-language-injection": {
                                        "language": "Handlebars"
                                      },
                                      "patternProperties": {
                                        "^.*$": {
                                          "x-intellij-language-injection": {
                                            "language": "Handlebars"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "headers": {
          "description": "Response headers",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "x-intellij-language-injection": {
                "language": "Handlebars"
              }
            }
          }
        },
        "transformers": {
          "description": "Enables predefined response transformations",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "response-template"
            ]
          }
        }
      }
    }
  },
  "required": [
    "request",
    "response"
  ]
}

=== beltram/stubr/tests/stubs/find-by-id.json
{
  "id": "82d86e05-9ee0-44ca-9a8d-1fc6f719437e",
  "request": {
    "urlPath": "/api/quizzes/5c235e338521b819587801ba/questions/5c86d46cdf7cd157ac050c25",
    "method": "GET",
    "headers": {
      "Authorization": {
        "equalTo": "Bearer TENANT_USER"
      },
      "Content-Type": {
        "equalTo": "application/json"
      }
    }
  },
  "response": {
    "status": 200,
    "body": "{\"label\":\"What is an immutable object\",\"level\":\"NOVICE\",\"answerOptions\":[{\"label\":\"An immutable object can be changed once it is created\",\"valid\":false,\"id\":\"5d680c5272bc809c3fafc3cc\"},{\"label\":\"An immutable object can't be changed once it is created\",\"valid\":true,\"id\":\"5d680c5272bc809c3fafc3cd\"},{\"label\":\" An immutable object is an instance of an abstract class\",\"valid\":false,\"id\":\"5d680c5272bc809c3fafc3ce\"},{\"label\":\"None of the above\",\"valid\":false,\"id\":\"5d680c5272bc809c3fafc3cf\"}],\"explanation\":\"Immutable objects cannot be changed once created. String, Integer or LocalDate are immutable objects. Hence thread safe\",\"configuration\":{\"duration\":\"PT30S\",\"code\":false,\"shuffle\":false},\"results\":[],\"id\":\"5c86d46cdf7cd157ac050c25\"}",
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": [
      "response-template"
    ]
  },
  "uuid": "82d86e05-9ee0-44ca-9a8d-1fc6f719437e"
}

=== beltram/stubr/tests/stubs/resp/body/json.json
{
  "id": "82d86e05-9ee0-44ca-9a8d-1fc6f719437e",
  "request": {
    "method": "GET"
  },
  "response": {
    "status": 200,
    "jsonBody": {
      "name": "john",
      "age": 42,
      "candidate": true,
      "surnames": [
        "jdoe",
        "johnny"
      ]
    }
  },
  "uuid": "82d86e05-9ee0-44ca-9a8d-1fc6f719437e"
}
